### ISSUE TITLE
More verbose p2p log output

### ISSUE THREAD

**Issue by jwasinger** [ethereum/aleth#5191]
~Reproducible example using docker-compose: https://github.com/jwasinger/cpp-eth-2-nodes~

**Comment by jwasinger** [comment]
Hold up... I don't have jsonrpcproxy working correctly on these containers.  let me add that and then confirm if it is still broken.

**Comment by jwasinger** [comment]
I set up two nodes and tried to get them to connect to each other (example here https://github.com/jwasinger/cpp-eth-2-nodes ).  In the logs, I get no indication that the nodes are trying to dial one another.

CC @gumb0 as I understand that the p2p code mostly falls under your purview.

**Comment by chfast** [comment]
@jwasinger Can you first try omitting the `enode://` prefix in the peerset option. Should look like `required:68e638...`.

**Comment by jwasinger** [comment]
Same result.

**Comment by jwasinger** [comment]
Same result @chfast

**Comment by gumb0** [comment]
Are these the arguments you run with?
```
--db-path /.ethereum --peerset "required:enode://68e6383c649935649723fc44bb4a94bd2019c29a828cb7ee8151abda9567417797fec213f4b60b59d84faac62577814d63cc5d7cc7d4bc09730ea4f43e9f44db@127.0.0.1:30303 required:enode://981a57a531a8e04dc44a31beddbaca772672d238c94d3da35dc420eb2398b6500d66121f83cb94d06b99df5b459376449458093ad149fc064133e10aae56ae3c@127.0.0.1:30304" --log-verbosity 12 --no-discover --no-bootstrap --pin --listen-ip 127.0.0.1 --listen 30303 --mining on --mode full --mining-threads 1 --address e2a6f75d132c092f63a4778d593713d2e44496a9 --config /ewasm-testnet-cpp-config.json
```
```
--db-path /.ethereum --peerset "required:enode://68e6383c649935649723fc44bb4a94bd2019c29a828cb7ee8151abda9567417797fec213f4b60b59d84faac62577814d63cc5d7cc7d4bc09730ea4f43e9f44db@127.0.0.1:30303 required:enode://981a57a531a8e04dc44a31beddbaca772672d238c94d3da35dc420eb2398b6500d66121f83cb94d06b99df5b459376449458093ad149fc064133e10aae56ae3c@127.0.0.1:30304" --log-verbosity 12 --no-discover --no-bootstrap --pin --listen-ip 127.0.0.1 --listen 30304 --mining on --mode full --mining-threads 1 --address e2a6f75d132c092f63a4778d593713d2e44496a9 --config /ewasm-testnet-cpp-config.json
```
If it's inside the same container, they should have different `--db-path` otherwise the second node won't be able to start because the database is already open.
`enode://` should be removed
Can you post the logs you get if it's still not working?

**Comment by gumb0** [comment]
On Windows I definitely see two nodes on one machine being able to connect and communicate.
The commands I used are
```
C:\dev\cpp-ethereum\build\aleth\Debug\aleth.exe --db-path keys\0 --peerset "required:68e6383c649935649723fc44bb4a94bd2019c29a828cb7ee8151abda9567417797fec213f4b60b59d84faac62577814d63cc5d7cc7d4bc09730ea4f43e9f44db@127.0.0.1:30303 required:981a57a531a8e04dc44a31beddbaca772672d238c94d3da35dc420eb2398b6500d66121f83cb94d06b99df5b459376449458093ad149fc064133e10aae56ae3c@127.0.0.1:30304" --log-verbosity 4 --no-discover --no-bootstrap --pin --listen-ip 127.0.0.1 --listen 30303 -m on --mode full --mining-threads 1 --address e2a6f75d132c092f63a4778d593713d2e44496a9 --config ewasm-testnet-cpp-config.json
```
```
C:\dev\cpp-ethereum\build\aleth\Debug\aleth.exe --db-path keys\1 --peerset "required:68e6383c649935649723fc44bb4a94bd2019c29a828cb7ee8151abda9567417797fec213f4b60b59d84faac62577814d63cc5d7cc7d4bc09730ea4f43e9f44db@127.0.0.1:30303 required:981a57a531a8e04dc44a31beddbaca772672d238c94d3da35dc420eb2398b6500d66121f83cb94d06b99df5b459376449458093ad149fc064133e10aae56ae3c@127.0.0.1:30304" --log-verbosity 4 --no-discover --no-bootstrap --pin --listen-ip 127.0.0.1 --listen 30304 -m on --mode full --mining-threads 1 --address e2a6f75d132c092f63a4778d593713d2e44496a9 --config ewasm-testnet-cpp-config.json
```
I'll try it on Linux, too

**Comment by gumb0** [comment]
p2p log is pretty verbose already, it's hard to say what kind of message we should add until we figure out what's @jwasinger's problem

**Comment by jwasinger** [comment]
Interesting.  Okay, I'm not exactly sure what the problem is then.  Have you seen the example I posted?  I don't see any kind of logging in the output of `docker-compose up` that indicates any dialing is going on.

**Comment by gumb0** [comment]
I see similar log on Linux (not in container)

**Comment by gumb0** [comment]
Ok looks like they don't connect for me either, when running with docker-compose

**Comment by gumb0** [comment]
But it does without `enode://`

@jwasinger try this (mining turned off for now to better see net logs)
```
version: '2'
services:
  node1:
    image: ethereum/aleth:1.4.0rc1
    ports:
      - "30303:30303"
      - "8545:8545"
    volumes:
      - ./keys/0:/.ethereum
      - ./ewasm-testnet-cpp-config.json:/ewasm-testnet-cpp-config.json
    command: --db-path /.ethereum --peerset "required:68e6383c649935649723fc44bb4a94bd2019c29a828cb7ee8151abda9567417797fec213f4b60b59d84faac62577814d63cc5d7cc7d4bc09730ea4f43e9f44db@127.0.0.1:30303 required:981a57a531a8e04dc44a31beddbaca772672d238c94d3da35dc420eb2398b6500d66121f83cb94d06b99df5b459376449458093ad149fc064133e10aae56ae3c@127.0.0.1:30304" --log-verbosity 12 --no-discover --no-bootstrap --pin --listen-ip 127.0.0.1 --listen 30303 --mining off --mode full --mining-threads 1 --address e2a6f75d132c092f63a4778d593713d2e44496a9 --config /ewasm-testnet-cpp-config.json
  node2:
    image: ethereum/aleth:1.4.0rc1
    ports:
      - "30304:30304"
      - "8546:8546"
    volumes:
      - ./keys/1:/.ethereum
      - ./ewasm-testnet-cpp-config.json:/ewasm-testnet-cpp-config.json
    command: --db-path /.ethereum --peerset "required:68e6383c649935649723fc44bb4a94bd2019c29a828cb7ee8151abda9567417797fec213f4b60b59d84faac62577814d63cc5d7cc7d4bc09730ea4f43e9f44db@127.0.0.1:30303 required:981a57a531a8e04dc44a31beddbaca772672d238c94d3da35dc420eb2398b6500d66121f83cb94d06b99df5b459376449458093ad149fc064133e10aae56ae3c@127.0.0.1:30304" --log-verbosity 12 --no-discover --no-bootstrap --pin --listen-ip 127.0.0.1 --listen 30304 --mining off --mode full --mining-threads 1 --address e2a6f75d132c092f63a4778d593713d2e44496a9 --config /ewasm-testnet-cpp-config.json
```
